#配置数据源datasoures
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
    schema: classpath:schema-@@platform@@.sql